export const image_url="https://plus.unsplash.com/premium_vector-1682306737276-670b799c9d1c?fm=jpg&q=60&w=3000&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
export const company_instagram = "https://www.instagram.com/bizmatehrofficial/"
export const company_facebook = "https://www.facebook.com/bizmatehr"
export const company_linkedin = "https://www.linkedin.com/company/bizmatehr/?viewAsMember=true"
export const company_twitter = "https://twitter.com/bizmatehr"
export const company_youtube = "https://www.youtube.com/@Bizmatehrsolutions"